import Head from "next/head";
import TodoList from "@/Components/TodoList/TodoList";
import { MongoClient } from "mongodb";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TodoList todos={props.todos}/>
    </>
  );
}

export async function getStaticProps() {
  const client = await MongoClient.connect(
    "mongodb+srv://MayankTiwari:x3vyqTqhpWEGXcwR@cluster0.qg8qp18.mongodb.net/todos?retryWrites=true&w=majority"
  );

  const db = client.db();

  const todoCollection = db.collection('todos');

  const todos = await todoCollection.find().toArray();

  const serializedTodos  = todos.map(todo => {
    return{
      ...todo,
      _id: todo._id.toString(),
    }
  })

  // client.close();

  return{
    props: {
      todos: serializedTodos
    },
    revalidate: 1,
  }
}
